# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-browsers
        environment:
          - APP_ENV: testing
          - APP_KEY: base64:2jlVzlGX4Yh4ooWODU4hinSatypNveXuFXPvBMwkKxM=
          - DB_CONNECTION: mysql_testing
          - DB_DATABASE_TESTING: testing_laravel_test
          - DB_USERNAME_TESTING: test
          - DB_PASSWORD_TESTING: test
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: testing_laravel_test
          - MYSQL_USER: test
          - MYSQL_PASSWORD: test
          - MYSQL_ROOT_HOST: %
          - TZ: Asia/Tokyo

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # wait for db
      - run: dockerize -wait tcp://localhost:3306 -timeout 1m
  
      - run: php artisan migrate --database=mysql_testing

      # run tests!
      - run: ./vendor/bin/phpunit
